using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Saber.GAS.Authoring;
using UnityEditor;
using UnityEngine;

namespace Saber.GAS.Editor
{
    internal static class GasGlobalCodeGenerator
    {
        private const string OutputFolder = "Assets/GAS/SaberGAS/Runtime/Generated";
        private const string OutputNamespace = "Saber.GAS.Generated";

        [MenuItem("Saber.GAS/Generate Global Id Code/For Selected Catalog", true)]
        private static bool ValidateGenerateForSelectedCatalogMenu()
        {
            return Selection.activeObject is CombatDefinitionCatalogAsset;
        }

        [MenuItem("Saber.GAS/Generate Global Id Code/For Selected Catalog")]
        private static void GenerateForSelectedCatalogMenu()
        {
            if (Selection.activeObject is CombatDefinitionCatalogAsset catalog)
            {
                GenerateForCatalog(catalog, true);
            }
        }

        [MenuItem("Saber.GAS/Generate Global Id Code/For All Catalogs")]
        private static void GenerateForAllCatalogsMenu()
        {
            GenerateForAllCatalogs(true);
        }

        public static IReadOnlyList<string> GenerateForAllCatalogs(bool focusLastGeneratedFile)
        {
            EnsureFolder(OutputFolder);

            var generatedPaths = new List<string>();
            var guids = AssetDatabase.FindAssets("t:CombatDefinitionCatalogAsset");
            for (var i = 0; i < guids.Length; i++)
            {
                var assetPath = AssetDatabase.GUIDToAssetPath(guids[i]);
                var catalog = AssetDatabase.LoadAssetAtPath<CombatDefinitionCatalogAsset>(assetPath);
                if (catalog == null)
                {
                    continue;
                }

                generatedPaths.Add(GenerateForCatalog(catalog, false));
            }

            if (focusLastGeneratedFile && generatedPaths.Count > 0)
            {
                GasEditorUtility.OpenAssetAtPath(generatedPaths[^1]);
            }

            Debug.Log(string.Format("Saber.GAS: 已为 {0} 份 Catalog 生成全局 Id 源码。", generatedPaths.Count));
            return generatedPaths;
        }

        public static string GenerateForCatalog(CombatDefinitionCatalogAsset catalog, bool focusGeneratedFile)
        {
            if (catalog == null)
            {
                return null;
            }

            EnsureFolder(OutputFolder);

            var className = ResolveClassName(catalog);
            var assetPath = OutputFolder + "/" + className + "Generated.cs";
            var legacyAssetPath = OutputFolder + "/" + className + ".g.cs";
            var absolutePath = Path.Combine(Path.GetDirectoryName(Application.dataPath) ?? string.Empty, assetPath);
            var source = BuildSource(catalog, className);

            var directory = Path.GetDirectoryName(absolutePath);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(absolutePath, source, new UTF8Encoding(false));
            DeleteLegacyFileIfExists(legacyAssetPath);
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);

            if (focusGeneratedFile)
            {
                GasEditorUtility.OpenAssetAtPath(assetPath);
            }

            Debug.Log(string.Format("Saber.GAS: 已生成全局 Id 源码 -> {0}", assetPath));
            return assetPath;
        }

        private static string BuildSource(CombatDefinitionCatalogAsset catalog, string className)
        {
            var tagEntries = CollectTagEntries(catalog);
            var resourceEntries = CollectResourceEntries(catalog);
            var builder = new StringBuilder(2048);

            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using Saber.GAS.Foundation;");
            builder.AppendLine("using Saber.GAS.Tags;");
            builder.AppendLine();
            builder.AppendLine("namespace " + OutputNamespace);
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 由 CombatDefinitionCatalogAsset 自动生成的全局 Tag / ResourceId 常量。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public static class " + className);
            builder.AppendLine("    {");
            builder.AppendLine("        public const string CatalogAssetName = \"" + EscapeString(catalog.name) + "\";");
            builder.AppendLine();

            AppendTagSection(builder, tagEntries);
            builder.AppendLine();
            AppendResourceSection(builder, resourceEntries);

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendTagSection(StringBuilder builder, List<GeneratedEntry> entries)
        {
            builder.AppendLine("        public static class Tags");
            builder.AppendLine("        {");
            if (entries.Count == 0)
            {
                builder.AppendLine("            public static readonly GameplayTag[] All = System.Array.Empty<GameplayTag>();");
                builder.AppendLine("            public static readonly string[] AllValues = System.Array.Empty<string>();");
                builder.AppendLine("        }");
                return;
            }

            for (var i = 0; i < entries.Count; i++)
            {
                AppendSummary(builder, entries[i]);
                builder.AppendLine("            public const string " + entries[i].FieldName + "Value = \"" + EscapeString(entries[i].RawValue) + "\";");
                builder.AppendLine("            public static readonly GameplayTag " + entries[i].FieldName + " = new GameplayTag(" + entries[i].FieldName + "Value);");
                builder.AppendLine();
            }

            builder.AppendLine("            public static readonly GameplayTag[] All =");
            builder.AppendLine("            {");
            for (var i = 0; i < entries.Count; i++)
            {
                builder.AppendLine("                " + entries[i].FieldName + ",");
            }
            builder.AppendLine("            };");
            builder.AppendLine();
            builder.AppendLine("            public static readonly string[] AllValues =");
            builder.AppendLine("            {");
            for (var i = 0; i < entries.Count; i++)
            {
                builder.AppendLine("                " + entries[i].FieldName + "Value,");
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
        }

        private static void AppendResourceSection(StringBuilder builder, List<GeneratedEntry> entries)
        {
            builder.AppendLine("        public static class Resources");
            builder.AppendLine("        {");
            if (entries.Count == 0)
            {
                builder.AppendLine("            public static readonly ResourceId[] All = System.Array.Empty<ResourceId>();");
                builder.AppendLine("            public static readonly string[] AllValues = System.Array.Empty<string>();");
                builder.AppendLine("        }");
                return;
            }

            for (var i = 0; i < entries.Count; i++)
            {
                AppendSummary(builder, entries[i]);
                builder.AppendLine("            public const string " + entries[i].FieldName + "Value = \"" + EscapeString(entries[i].RawValue) + "\";");
                builder.AppendLine("            public static readonly ResourceId " + entries[i].FieldName + " = new ResourceId(" + entries[i].FieldName + "Value);");
                builder.AppendLine();
            }

            builder.AppendLine("            public static readonly ResourceId[] All =");
            builder.AppendLine("            {");
            for (var i = 0; i < entries.Count; i++)
            {
                builder.AppendLine("                " + entries[i].FieldName + ",");
            }
            builder.AppendLine("            };");
            builder.AppendLine();
            builder.AppendLine("            public static readonly string[] AllValues =");
            builder.AppendLine("            {");
            for (var i = 0; i < entries.Count; i++)
            {
                builder.AppendLine("                " + entries[i].FieldName + "Value,");
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
        }

        private static void AppendSummary(StringBuilder builder, GeneratedEntry entry)
        {
            var summaryParts = new List<string> { "原值: " + entry.RawValue };
            if (!string.IsNullOrWhiteSpace(entry.Group))
            {
                summaryParts.Add("分组: " + entry.Group);
            }

            if (!string.IsNullOrWhiteSpace(entry.Usage))
            {
                summaryParts.Add("用途: " + entry.Usage);
            }

            if (!string.IsNullOrWhiteSpace(entry.Note))
            {
                summaryParts.Add("备注: " + entry.Note);
            }

            builder.AppendLine("            /// <summary>");
            builder.AppendLine("            /// " + EscapeXml(string.Join(" | ", summaryParts.ToArray())));
            builder.AppendLine("            /// </summary>");
        }

        private static List<GeneratedEntry> CollectTagEntries(CombatDefinitionCatalogAsset catalog)
        {
            var results = new List<GeneratedEntry>();
            var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);
            var seenValues = new HashSet<string>(StringComparer.Ordinal);
            var definitions = catalog.GlobalTagDefinitions == null
                ? Array.Empty<CombatTagDefinitionAuthoringData>()
                : catalog.GlobalTagDefinitions
                    .Where(definition => definition != null && !string.IsNullOrWhiteSpace(definition.Tag))
                    .OrderBy(definition => definition.Group, StringComparer.OrdinalIgnoreCase)
                    .ThenBy(definition => definition.Tag, StringComparer.OrdinalIgnoreCase)
                    .ToArray();

            for (var i = 0; i < definitions.Length; i++)
            {
                var value = definitions[i].Tag.Trim();
                if (!seenValues.Add(value))
                {
                    continue;
                }

                results.Add(new GeneratedEntry
                {
                    RawValue = value,
                    FieldName = MakeUniqueIdentifier(ToPascalIdentifier(value), usedFieldNames),
                    Group = definitions[i].Group,
                    Usage = definitions[i].Usage.ToString(),
                    Note = definitions[i].Note,
                });
            }

            return results;
        }

        private static List<GeneratedEntry> CollectResourceEntries(CombatDefinitionCatalogAsset catalog)
        {
            var results = new List<GeneratedEntry>();
            var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);
            var seenValues = new HashSet<string>(StringComparer.Ordinal);
            var definitions = catalog.GlobalResourceDefinitions == null
                ? Array.Empty<CombatResourceDefinitionAuthoringData>()
                : catalog.GlobalResourceDefinitions
                    .Where(definition => definition != null && !string.IsNullOrWhiteSpace(definition.ResourceId))
                    .OrderBy(definition => definition.Group, StringComparer.OrdinalIgnoreCase)
                    .ThenBy(definition => definition.ResourceId, StringComparer.OrdinalIgnoreCase)
                    .ToArray();

            for (var i = 0; i < definitions.Length; i++)
            {
                var value = definitions[i].ResourceId.Trim();
                if (!seenValues.Add(value))
                {
                    continue;
                }

                results.Add(new GeneratedEntry
                {
                    RawValue = value,
                    FieldName = MakeUniqueIdentifier(ToPascalIdentifier(value), usedFieldNames),
                    Group = definitions[i].Group,
                    Note = definitions[i].Note,
                });
            }

            return results;
        }

        private static string ResolveClassName(CombatDefinitionCatalogAsset catalog)
        {
            var baseName = ToPascalIdentifier(catalog == null ? string.Empty : catalog.name);
            if (string.IsNullOrWhiteSpace(baseName))
            {
                baseName = "CombatCatalog";
            }

            var guid = catalog == null
                ? string.Empty
                : AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(catalog));
            var allCatalogGuids = AssetDatabase.FindAssets("t:CombatDefinitionCatalogAsset");
            var hasDuplicateName = false;
            for (var i = 0; i < allCatalogGuids.Length; i++)
            {
                if (allCatalogGuids[i] == guid)
                {
                    continue;
                }

                var assetPath = AssetDatabase.GUIDToAssetPath(allCatalogGuids[i]);
                var otherCatalog = AssetDatabase.LoadAssetAtPath<CombatDefinitionCatalogAsset>(assetPath);
                if (otherCatalog == null)
                {
                    continue;
                }

                if (string.Equals(ToPascalIdentifier(otherCatalog.name), baseName, StringComparison.Ordinal))
                {
                    hasDuplicateName = true;
                    break;
                }
            }

            if (hasDuplicateName && !string.IsNullOrWhiteSpace(guid) && guid.Length >= 8)
            {
                baseName += "G" + guid.Substring(0, 8).ToUpperInvariant();
            }

            return baseName.EndsWith("Ids", StringComparison.Ordinal) ? baseName : baseName + "Ids";
        }

        private static string ToPascalIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "Value";
            }

            var builder = new StringBuilder(value.Length);
            var capitalize = true;
            for (var i = 0; i < value.Length; i++)
            {
                var c = value[i];
                if (!char.IsLetterOrDigit(c))
                {
                    capitalize = true;
                    continue;
                }

                if (builder.Length == 0 && char.IsDigit(c))
                {
                    builder.Append('N');
                }

                builder.Append(capitalize ? char.ToUpperInvariant(c) : c);
                capitalize = false;
            }

            return builder.Length == 0 ? "Value" : builder.ToString();
        }

        private static string MakeUniqueIdentifier(string baseName, HashSet<string> usedFieldNames)
        {
            var candidate = string.IsNullOrWhiteSpace(baseName) ? "Value" : baseName;
            if (usedFieldNames.Add(candidate))
            {
                return candidate;
            }

            for (var i = 2; i < 1000; i++)
            {
                var unique = candidate + i;
                if (usedFieldNames.Add(unique))
                {
                    return unique;
                }
            }

            return candidate + "999";
        }

        private static string EscapeString(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }

        private static string EscapeXml(string value)
        {
            return (value ?? string.Empty)
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        private static void EnsureFolder(string folderPath)
        {
            var segments = folderPath.Split('/');
            var current = segments[0];
            for (var i = 1; i < segments.Length; i++)
            {
                var next = current + "/" + segments[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, segments[i]);
                }

                current = next;
            }
        }

        private static void DeleteLegacyFileIfExists(string assetPath)
        {
            if (string.IsNullOrWhiteSpace(assetPath) || !File.Exists(Path.Combine(Path.GetDirectoryName(Application.dataPath) ?? string.Empty, assetPath)))
            {
                return;
            }

            AssetDatabase.DeleteAsset(assetPath);
        }

        private sealed class GeneratedEntry
        {
            public string RawValue;
            public string FieldName;
            public string Group;
            public string Usage;
            public string Note;
        }
    }
}
